# -*- coding: utf-8 -*-
"""MLOM_Lab9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pxHoj8LQqkkGtfrjLVPUKZErPik6z_dR
"""

#data manipulation and analysis
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,cross_val_score
#support vector classification
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

df = pd.read_csv("/content/diabetes.csv")

df.head()

df.shape

# Import the diabetes dataset to the Python environment
#: = select each and every raw
x = df.iloc[:,0:8].values
print(x)

y = df.iloc[:,8].values
print(y)

# Split the data into training & testing
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

# C=1 moderator value
model = SVC(C=1,kernel="linear") #others are poly, RBF

#training model
model.fit(x_train,y_train)

y_pred = model.predict(x_test)

accuracy_score(y_test,y_pred)

#evaluate model
confusion_matrix(y_test,y_pred)

#classification report
print(classification_report(y_test,y_pred))

#Cross Validation approach, find the prediction accuracy using the same SVM model.(compare to like 18)
accs = cross_val_score(model,x,y,cv=5,scoring="accuracy")

accs

np.mean(accs)

